# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-20 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cf_app', '0005_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='user',
        ),
    ]
