# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 17:11
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf_app', '0006_remove_candidateprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='streak_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(default='noemail', max_length=254), default=[], size=None),
            preserve_default=False,
        ),
    ]
