# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf_app', '0008_auto_20161217_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.URLField(default='http://none.com'),
        ),
    ]
