# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cf_app', '0010_auto_20161218_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='title',
            new_name='job_title',
        ),
    ]
